import java.util.ArrayList;
import java.util.List;
import java.util.Random;

class Question {
    String question;
    String english;
    String answer;
    String[] hint= new String[7]; // ヒントを配列で保持

    public Question(String question,String english, String answer, String[] hint) {
        this.question = question;
        this.english = english;
        this.answer = answer;
        this.hint = hint;
    }
}

public class App {
    List<Question> questions = new ArrayList<>();

    public App() {
        /*questions.add(new Question("日本の首都は？", "Tokyo", "東京", new String[]{"本州の東の方だよ","日本の首都だよ", "東京タワーがあるよ", "東京ディズニーランドがあるよ", "新幹線が通っているよ", "オリンピックが開催されたよ", "多くの人が住んでいるよ"}));
        questions.add(new Question("Javaは何語で開発された？", "English", "英語", new String[]{"Sun Microsystemsで開発されたよ", "アメリカで開発されたよ", "Javaの文法は英語に似ているよ", "Javaのキーワードは英語だよ", "Javaのドキュメントは英語で書かれているよ", "Javaの公式サイトは英語だよ", "Javaのコミュニティも英語が主流だよ"}));
        questions.add(new Question("2 + 2 は？", "4","4", new String[]{"基本的な算数の問題だよ"}));*/
        questions.add(new Question("愛と憎しみを合わせたものを何という？","Love And Hate","愛憎",new String[]{"「感情に所属しており、応用感情、基本感情、強い感情、弱い感情のどれにも位置しない」","反対の語句が並んでいる","○○の念が入り混じる","○○相半ばする","特に相手に対して好悪の感情を抱くこと","一組の存在達の間に生じる全く対照的な感情"}));
        questions.add(new Question("期待と喜びを合わせたものを何という？","Optimism (=Anticipation +Joy)","楽観",new String[]{"「感情に所属しており、応用感情に位置している」","世界を軽く考えている","物事の先行きを良い方に考えて心配しない事","心配するほどのことではないとして気楽に考えること","病状は○○を許さない","状況を○○する"}));
        questions.add(new Question("嫌悪と喜びを合わせたものを何という？","Morbidness (=Disgust +Joy)","病的状態",new String[]{"「感情に所属しており、応用感情に位置している」","不健全な状態であること","健康を害するような状態であること","精神的に不安定な状態であること","常軌を逸した状態であること","異常な状態であること"}));
        questions.add(new Question("怒りと期待を合わせたものを何という？","Aggressiveness (=Anger +Anticipation)","積極性",new String[]{"「感情に所属しており、応用感情に位置している」","自分の価値や能力を高く評価すること","自分の行動や成果に満足すること","自分の所属する集団や国に対して誇りを持つこと","自分の信念や価値観を大切にすること","自分の存在意義を感じること"}));
        questions.add(new Question("怒りと喜びを合わせたものを何という？","Pride(=Anger +Joy)","誇り",new String[]{"「感情に所属しており、応用感情に位置している」","物事に進んで取り組む様子","自分から進んで行動すること","前向きに物事に取り組むこと","積極的に行動すること","積極的な態度を持つこと"}));
        questions.add(new Question("嫌悪と期待を合わせたものを何という？","Cynicism (=Disgust +Anticipation)","冷笑",new String[]{"「感情に所属しており、応用感情に位置している」","物事に進んで取り組む様子","自分から進んで行動すること","前向きに物事に取り組むこと","積極的に行動すること","積極的な態度を持つこと"}));
        questions.add(new Question("悲しみと期待を合わせたものを何という？","Pessimism (=Sadness +Anticipation)","悲観",new String[]{"「感情に所属しており、応用感情に位置している」","他人の言動や考えに対して否定的な態度を持つこと","他人の動機や意図を疑うこと","他人の善意を信じないこと","他人の行動を信用しないこと","他人の言動を軽蔑すること"}));
        questions.add(new Question("嫌悪と怒りを合わせたものを何という？","Contempt (=Disgust +Anger)","軽蔑",new String[]{"「感情に所属しており、応用感情に位置している」","他人の言動や考えを軽蔑すること","他人の動機や意図を軽蔑すること","他人の善意を軽蔑すること","他人の行動を軽蔑すること","他人の存在を軽蔑すること"}));
        questions.add(new Question("悲しみと怒りを合わせたものを何という？","Envy (=Sadness +Anger)","嫉妬",new String[]{"「感情に所属しており、応用感情及び七大罪に位置している」","他人の成功や幸福を妬むこと","他人の能力や才能を妬むこと","他人の財産や地位を妬むこと","他人の愛情や関心を妬むこと","他人の注目や称賛を妬むこと"}));
        questions.add(new Question("驚きと怒りを合わせたものを何という？","Outrage (=Surprise +Anger)","憤慨",new String[]{"「感情に所属しており、応用感情に位置している」","不正なことに対して強い怒りを感じること","不公平なことに対して強い怒りを感じること","不当なことに対して強い怒りを感じること","不義なことに対して強い怒りを感じること","不快なことに対して強い怒りを感じること","けしからぬ事に対していきどおりなげくこと"}));
        questions.add(new Question("悲しみと嫌悪を合わせたものを何という？","Remorse (=Sadness +Disgust)","自責",new String[]{"「感情に所属しており、応用感情に位置している」","自分の行動や言動に対して強い嫌悪感を感じること","自分の過ちに対して強い嫌悪感を感じること","自分の失敗に対して強い嫌悪感を感じること","自分の欠点に対して強い嫌悪感を感じること","自分自身に対して強い嫌悪感を感じること","自分で自分の過ちを責めること"}));
        questions.add(new Question("驚きと嫌悪を合わせたものを何という？","Unbelief (=Surprise +Disgust)","不信",new String[]{"「感情に所属しており、応用感情に位置している」","他人の言動を信用しないこと","他人の動機を信じないこと","他人の善意を信じないこと","他人の行動を信用しないこと","他人の言動を疑うこと","他人の言動を疑うこと","信用しない事"}));
        questions.add(new Question("恐れと嫌悪を合わせたものを何という？","Shame (=Fear +Disgust)","恥",new String[]{"「感情に所属しており、応用感情に位置している」","自分の行動や言動に対して強い恥ずかしさを感じること","自分の過ちに対して強い恥ずかしさを感じること","自分の失敗に対して強い恥ずかしさを感じること","自分の欠点に対して強い恥ずかしさを感じること","自分自身に対して強い恥ずかしさを感じること","社会的な規範や期待に反する行動をしたときに感じる不快な感情"}));
        questions.add(new Question("驚きと悲しみを合わせたものを何という？","Disappointment (=Surprise +Sadness)","失望",new String[]{"「感情に所属しており、応用感情に位置している」","期待していたことが実現しなかったときに感じる失望感","希望していたことが叶わなかったときに感じる失望感","願っていたことが達成されなかったときに感じる失望感","楽しみにしていたことが実現しなかったときに感じる失望感","予想していたことが外れたときに感じる失望感"}));
        questions.add(new Question("恐れと悲しみを合わせたものを何という？","Despair (=Fear +Sadness)","絶望",new String[]{"「感情に所属しており、応用感情及び負の感情に位置している」","将来に対して希望を失うこと","未来に対して希望を失うこと","未知に対して希望を失うこと","不確実なことに対して希望を失うこと","予測できないことに対して希望を失うこと","望みが絶たれた状態 "}));
        questions.add(new Question("信頼と悲しみを合わせたものを何という？","Sentimentality (=Trust +Sadness)","感傷",new String[]{"「感情に所属しており、応用感情及び負の感情に位置している」","過去の出来事や思い出に対して強い感傷を感じること","失われたものに対して強い感傷を感じること","失った人や物に対して強い感傷を感じること","過ぎ去った時間に対して強い感傷を感じること","懐かしいものに対して強い感傷を感じること","過去の出来事や思い出に対して強い感傷を感じること"}));
        questions.add(new Question("恐れと驚きを合わせたものを何という？","Awe (=Fear +Surprise)","畏敬",new String[]{"「感情に所属しており、応用感情に位置している」","自然の偉大さや神秘に対して強い畏敬の念を抱くこと","宇宙の広大さや未知に対して強い畏敬の念を抱くこと","宗教的な存在や神聖なものに対して強い畏敬の念を抱くこと","歴史的な偉人や文化遺産に対して強い畏敬の念を抱くこと","芸術作品や音楽に対して強い畏敬の念を抱くこと","尊敬と恐れが入り混じった感情"}));
        questions.add(new Question("信頼と驚きを合わせたものを何という？","Curiosity (=Trust +Surprise)","好奇心",new String[]{"「感情に所属しており、応用感情に位置している」","新しいことに興味を持つこと","未知のことに興味を持つこと","知らないことに興味を持つこと","新しい経験に興味を持つこと","新しい知識に興味を持つこと","物事を探究しようとする根源的な心 "}));
        questions.add(new Question("喜びと驚きを合わせたものを何という？","Delight (=Joy +Surprise)","歓喜",new String[]{"「感情に所属しており、応用感情に位置している」","非常に嬉しいと感じること","非常に楽しいと感じること","非常に幸せと感じること","非常に満足と感じること","非常に喜ばしいと感じること","心からの喜び"}));
        questions.add(new Question("信頼と恐れを合わせたものを何という？","Submission (=Trust +Fear)","服従",new String[]{"「感情に所属しており、応用感情に位置している」","他人の意見や考えを受け入れること","他人の価値観や信念を受け入れること","他人の行動や習慣を受け入れること","他人の違いを受け入れること","他人の多様性を受け入れること","権威や力に対して従うこと"}));
        questions.add(new Question("喜びと恐れを合わせたものを何という？","Guilt (=Joy +Fear)","罪悪感",new String[]{"「感情に所属しており、応用感情に位置している」","自分の行動や言動に対して強い罪悪感を感じること","自分の過ちに対して強い罪悪感を感じること","自分の失敗に対して強い罪悪感を感じること","自分の欠点に対して強い罪悪感を感じること","自分自身に対して強い罪悪感を感じること","道徳的な規範や価値観に反する行動をしたときに感じる不快な感情"}));
        questions.add(new Question("期待と恐れを合わせたものを何という？","Anxiety (=Anticipation +Fear)","不安",new String[]{"「感情に所属しており、応用感情及び負の感情に位置している」","将来に対して強い不安を感じること","未来に対して強い不安を感じること","未知に対して強い不安を感じること","不確実なことに対して強い不安を感じること","予測できないことに対して強い不安を感じること"}));
        questions.add(new Question("喜びと信頼を合わせたものを何という？","Love (=Joy +Trust)","愛",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","気持ちよく明るいkibunn だ","他人に対して強い好意を持つこと","他人に対して強い親しみを持つこと","他人に対して強い思いやりを持つこと","他人に対して強い献身を持つこと","他人に対して強い共感を持つこと","誰もが普通（不通）に経験する神経質、心配、困惑の感情 "}));
        questions.add(new Question("期待と信頼を合わせたものを何という？","Hope (=Anticipation +Trust)","希望",new String[]{"「感情に所属しており、応用感情に位置している」","将来に対して良いことを期待すること","未来に対して良いことを期待すること","未知に対して良いことを期待すること","不確実なことに対して良いことを期待すること","予測できないことに対して良いことを期待すること","大事なものとして慕う心 "}));
        questions.add(new Question("怒りと信頼を合わせたものを何という？","Dominance (=Anger +Trust)","優位",new String[]{"「感情に所属しており、応用感情に位置している」","他人に対して強い支配欲を持つこと","他人に対して強い影響力を持つこと","他人に対して強い権力を持つこと","他人に対して強い統率力を持つこと","他人に対して強いリーダーシップを持つこと","他人よりも優れていると感じること","他より立ちまさった(有利な)位置や立場"}));
        questions.add(new Question("喜怒哀楽から喜と哀と怒を外し、「しい」を合わせたものを何という？","Enjoy (=joy, anger, sadness, Enjoy -joy -anger -sadness)","楽しい",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","気持ちよく明るい気分だ","非常に嬉しいと感じること","非常に楽しいと感じること","非常に幸せと感じること","非常に満足と感じること","非常に喜ばしいと感じること"}));
        questions.add(new Question("嬉笑怒罵から嬉しいと罵るを外したものを何という？","Anger (=Happy laughing angry cursing -happy -laugh -curse)","怒り",new String[]{"「感情に所属しており、基本感情に位置している」","不快なことに対して強い不満を感じること","不正なことに対して強い不満を感じること","不公平なことに対して強い不満を感じること","不当なことに対して強い不満を感じること","不義なことに対して強い不満を感じること"}));
        questions.add(new Question("哀哀父母から哀しい一つと父と母を外したものを何という？","Sad (=grieving parents -A sad one -father -mother)","悲しみ",new String[]{"「感情に所属しており、基本感情に位置している」","失ったものに対して深い悲しみを感じること","失敗したことに対して深い悲しみを感じること","裏切られたことに対して深い悲しみを感じること","絶望したことに対して深い悲しみを感じること","孤独を感じたことに対して深い悲しみを感じること"}));
        questions.add(new Question("愛別離苦から別れる離れると愛するを外したものを何という？","Grief (=separation pain -Love -break up -Leave)","悲痛",new String[]{"「感情に所属しており、基本感情に位置している」","危険なことに対して強い不安を感じること","未知のことに対して強い不安を感じること","不確実なことに対して強い不安を感じること","予測できないことに対して強い不安を感じること","将来に対して強い不安を感じること"}));
        questions.add(new Question("狂喜乱舞から狂うと乱れると舞うを外したものを何という？","Joy (=Crazy dance -go crazy -be disturbed -dance)","喜び",new String[]{"「感情に所属しており、基本感情に位置している」","予期しないことに対して強い驚きを感じること","突然のことに対して強い驚きを感じること","意外なことに対して強い驚きを感じること","不可解なことに対して強い驚きを感じること","信じられないことに対して強い驚きを感じること"}));
        questions.add(new Question("恐恐謹言から恐れ一つと謹言を外したものを何という？","Fear (=I apologize for the inconvenience -one fear -Greetings)","恐れ",new String[]{"「感情に所属しており、基本感情に位置している」","不快なことに対して強い嫌悪感を感じること","不潔なことに対して強い嫌悪感を感じること","不道徳なことに対して強い嫌悪感を感じること","不正なことに対して強い嫌悪感を感じること","不公平なことに対して強い嫌悪感を感じること"}));
        questions.add(new Question("驚心動魄から心と動くと魄を外したものを何という？","Surprise (=Shocking heart -heart -move -spirit)","驚き",new String[]{"「感情に所属しており、基本感情に位置している」","他人の言動を信用すること","他人の動機を信じること","他人の善意を信じること","他人の行動を信じること","他人の言動を信じること"}));
        questions.add(new Question("自己嫌悪から自己を外したものを何という？","Disgust (=self hate-self)","嫌悪",new String[]{"自分自身に対して強い嫌悪感を感じること","自分の行動や言動に対して強い嫌悪感を感じること","自分の過ちに対して強い嫌悪感を感じること","自分の失敗に対して強い嫌悪感を感じること","自分の欠点に対して強い嫌悪感を感じること"}));
        questions.add(new Question("期待値から値を外したものを何という？","Anticipation (=Expected value -value)","期待",new String[]{"将来に対して良いことを期待すること","未来に対して良いことを期待すること","未知に対して良いことを期待すること","不確実なことに対して良いことを期待すること","予測できないことに対して良いことを期待すること"}));
        questions.add(new Question("信頼度成長曲線から度と成長曲線を外したものを何という？","Trust (=Confidence growth curve -degree -growth curve)","信頼",new String[]{"他人の言動を信用すること","他人の動機を信じること","他人の善意を信じること","他人の行動を信じること","他人の言動を信じること"}));
        questions.add(new Question("恍惚の人からのと人を外したものを何という？","Ecstasy (=ecstatic person -of -person)","恍惚",new String[]{"非常に嬉しいと感じること","非常に楽しいと感じること","非常に幸せと感じること","非常に満足と感じること","非常に喜ばしいと感じること"}));
        questions.add(new Question("警戒区域から区域を外したものを何という？","Vigilance (=restricted area -area)","警戒",new String[]{"危険なことに対して強い注意を払うこと","未知のことに対して強い注意を払うこと","不確実なことに対して強い注意を払うこと","予測できないことに対して強い注意を払うこと","将来に対して強い注意を払うこと"}));
        questions.add(new Question("激怒症候群から症候群を外したものを何という？","Rage (=rage syndrome -syndrome)","激怒",new String[]{"非常に強い怒りを感じること","非常に強い不満を感じること","非常に強い憤りを感じること","非常に強い憎しみを感じること","非常に強い敵意を感じること"}));
        questions.add(new Question("憎悪の念からのと念を外したものを何という？","Loathing (=thoughts of hatred -of -Thought)","憎悪",new String[]{"他人に対して強い敵意を持つこと","他人に対して強い憎しみを持つこと","他人に対して強い反感を持つこと","他人に対して強い嫌悪感を持つこと","他人に対して強い軽蔑を持つこと"}));
        questions.add(new Question("驚嘆の声からのと声を外したものを何という？","Amazement (=amazing -to -worthy)","驚嘆",new String[]{"非常に強い驚きを感じること","非常に強い感動を感じること","非常に強い感激を感じること","非常に強い畏敬の念を感じること","非常に強い尊敬の念を感じること"}));
        questions.add(new Question("恐怖しろ！からしろと！を外したものを何という？","Terror (=Be afraid! -do -!)","恐怖",new String[]{"非常に強い恐れを感じること","非常に強い不安を感じること","非常に強い心配を感じること","非常に強い懸念を感じること","非常に強い危機感を感じること"}));
        questions.add(new Question("感嘆符から符を外したものを何という？","Admiration (=Exclamation point -sign)","感嘆",new String[]{"他人の行動や成果に対して強い敬意を抱くこと","他人の能力や才能に対して強い敬意を抱くこと","他人の努力や成果に対して強い敬意を抱くこと","他人の人格や人柄に対して強い敬意を抱くこと","他人の存在や価値に対して強い敬意を抱くこと"}));
        questions.add(new Question("平穏無事から無事を外したものを何という？","Serenity (=Peaceful and safe -safely)","平穏",new String[]{"心が穏やかであること","心が安らかであること","心が落ち着いていること","心が平和であること","心が静かであること"}));
        questions.add(new Question("興味津々から津々を外したものを何という？","Interest (=Interesting -all over)","興味",new String[]{"新しいことに興味を持つこと","未知のことに興味を持つこと","知らないことに興味を持つこと","新しい経験に興味を持つこと","新しい知識に興味を持つこと"}));
        questions.add(new Question("煩雑世界から雑と世界を外したものを何という？？","Annoyance (=complicated world -rough -world)","煩さ",new String[]{"不快なことに対して強い不満を感じること","不正なことに対して強い不満を感じること","不公平なことに対して強い不満を感じること","不当なことに対して強い不満を感じること","不義なことに対して強い不満を感じること"}));
        questions.add(new Question("憂鬱な未来から鬱なと未来を外したものを何という？","Pensiveness (=gloomy future -Depressed -future)","憂い",new String[]{"将来に対して心配すること","未来に対して心配すること","未知に対して心配すること","不確実なことに対して心配すること","予測できないことに対して心配すること"}));
        questions.add(new Question("退屈な日々からな日々を外したものを何という？","Boredom (=boredom psychology -psychology)","退屈",new String[]{"興味や関心が持てない状態","刺激がない状態","単調な状態","変化がない状態","新鮮さがない状態"}));
        questions.add(new Question("動揺性歩行から性と歩行を外したものを何という？","Distraction (=agitated gait -gender -walking)","動揺",new String[]{"強い不安や心配を感じる状態","強いストレスを感じる状態","強い緊張を感じる状態","強い混乱を感じる状態","強い困難を感じる状態"}));
        questions.add(new Question("心配事から事を外したものを何という？","Apprehension (=Anxiety -case)","心配",new String[]{"将来に対して注意を払うこと","未来に対して注意を払うこと","未知に対して注意を払うこと","不確実なことに対して注意を払うこと","予測できないことに対して注意を払うこと"}));
        questions.add(new Question("容認発音から発音外したものを何という？","Acceptance (acceptable pronunciation -pronunciation)","容認",new String[]{"他人の意見や考えを受け入れること","他人の価値観や信念を受け入れること","他人の行動や習慣を受け入れること","他人の違いを受け入れること","他人の多様性を受け入れること"}));
        questions.add(new Question("笑われるとコンプレックスから生み出されるものは何？","Arrogance (=be laughed at* Complex)","傲慢",new String[]{"「感情に所属しており、七大罪に位置している」","高ぶって人を侮り見下す態度であること","自分を過大評価し他人を軽視する態度であること","自分の能力や価値を過信し他人を見下す態度であること","自分の地位や権力を誇示し他人を侮る態度であること","自分の成功や成果を誇り他人を軽蔑する態度であること","他人よりも優れていると感じること"}));
        questions.add(new Question("理性消失と本能的殺戮から生み出されるものは何？","Wrath (=Reason disappears* Instinctive massacre)","憤怒",new String[]{"「感情に所属しており、七大罪及び負の感情に位置している」","非常に強い怒りを感じること","非常に強い不満を感じること","非常に強い憤りを感じること","非常に強い憎しみを感じること","非常に強い敵意を感じること","「つかみかからんばかりの恐ろしい形相で、激しく怒る事」"}));
        questions.add(new Question("周囲大幅消費と自己効率から生み出されるものは何？","Lazy (=The neighborhood large consumption* Self efficiency)","怠惰",new String[]{"「感情に所属しており、七大罪に位置している」","仕事や責任を避けること","努力や勤勉を避けること","活動や運動を避けること","挑戦や困難を避けること","変化や新しいことを避けること","「仕事や責任を怠ける事」"}));
        questions.add(new Question("殺害相手からランダムに一部略奪と満たされない欲望から生み出されるものは何？","Greed (=I plunder the killing partner of it partly at random* The greed that is not satisfied)","強欲",new String[]{"「感情に所属しており、七大罪に位置している」","必要以上に多くのものを求めること","過剰に多くのものを求めること","際限なく多くのものを求めること","無制限に多くのものを求めること","際限なく多くの富や財産を求めること","「むさぼり欲しがる事」"}));
        questions.add(new Question("あらゆるものを対象に食すことが可能と永久空腹から生み出されるものは何？","Gluttony (=I can eat it targeting at every thing* Eternity hunger)","暴食",new String[]{"「感情に所属しており、七大罪に位置している」","必要以上に多くの食べ物を摂取すること","過剰に多くの食べ物を摂取すること","際限なく多くの食べ物を摂取すること","無制限に多くの食べ物を摂取すること","際限なく多くの食べ物や飲み物を摂取すること","「むさぼり食う事」"}));
        questions.add(new Question("相手に「催眠」「魅了」「洗脳」の状態異常を付与と激しい嫌悪感から生み出されるものは何？","Lust (=I give state abnormality of the hypnos is charm brainwashing to a partner* Intense loathsomeness)","色欲",new String[]{"「感情に所属しており、七大罪に位置している」","過度に性的な欲望を持つこと","過剰に性的な欲望を持つこと","際限なく性的な欲望を持つこと","無制限に性的な欲望を持つこと","際限なく性的な快楽を求めること","「むさぼり欲しがる事」"}));
        questions.add(new Question("死者蘇生と禁忌から生み出され、自己を省くものは何？","Mercy (=resurrection of the dead* Taboo/self)","慈悲",new String[]{"「感情に所属しており、七大罪の対義語に位置している」","他人に対して強い思いやりを持つこと","他人に対して強い優しさを持つこと","他人に対して強い寛容さを持つこと","他人に対して強い同情心を持つこと","他人に対して強い愛情を持つこと","他人の苦しみや困難を理解し、助けようとする心"}));
        questions.add(new Question("死亡回避と防御・抵抗の能力上昇と耐性系熟練度補正から生み出され、我慢を省くものは何？","Patience (=death avoidance* Defense /resistance ability increase and resistance proficiency correction* Resistance proficiency correction /Patience)","忍耐",new String[]{"「感情に所属しており、七大罪の対義語に位置している」","困難や苦痛に耐えることができる能力","逆境や試練に耐えることができる能力","ストレスやプレッシャーに耐えることができる能力","挑戦や困難に立ち向かうことができる能力","不快な状況に耐えることができる能力","困難な状況でも冷静さを保ち、前向きに対処する力"}));
        questions.add(new Question("魂移す侵食乗っ取りと半分不死から生み出され、他者の意思を省くものは何？","Diligence (=Erosion takeover to move the soul* half immortal /the will of others)","勤勉",new String[]{"「感情に所属しており、七大罪の対義語に位置している」","仕事や責任を積極的に果たすこと","努力や勤勉を積極的に果たすこと","活動や運動を積極的に果たすこと","挑戦や困難を積極的に果たすこと","変化や新しいことを積極的に果たすこと","仕事や責任を熱心に取り組むこと"}));
        questions.add(new Question("自身を中心に自己及び味方へ体力超速回復と寄付から生み出され、ストックを省くものは何？","Relief(=Super fast recovery of physical strength to self and allies* donation /stock)","救恤",new String[]{"「感情に所属しており、七大罪の対義語に位置している」","他人を助けることに熱心であること","他人を支援することに熱心であること","他人を援助することに熱心であること","他人を救うことに熱心であること","他人を保護することに熱心であること","困っている人々を助け、支援する心"}));
        questions.add(new Question("前世の記憶保持状態での転生可能と実質不死から生み出され、不正を省くものは何？","Temperance (=Reincarnation with memory of previous life retained* Practically immortal /fraud)","節制",new String[]{"「感情に所属しており、七大罪の対義語に位置している」","欲望や衝動を抑えることができる能力","誘惑や誘惑に打ち勝つことができる能力","過度な行動を抑えることができる能力","過剰な行動を抑えることができる能力","無制限な行動を抑えることができる能力","欲望や衝動をコントロールし、バランスの取れた生活を送る力"}));
        questions.add(new Question("魂を消費して神と同等の力を得ると対等な立場から生み出され、不快感を省くものは何？","Humility (=Consume your soul to gain power equal to that of a god* equal position /Discomfort)","謙譲",new String[]{"「感情に所属しており、七大罪の対義語に位置している」","自分を過小評価し他人を尊重する態度であること","自分の能力や価値を控えめに評価し他人を尊重する態度であること","自分の地位や権力を誇示せず他人を尊重する態度であること","自分の成功や成果を誇らず他人を尊重する態度であること","自分よりも他人を優先し他人を尊重する態度であること","他人に対して謙虚であり、自己中心的でない心"}));
        questions.add(new Question("自身の持つ神性領域を拡張すると強力な結界を展開するから生み出され、性的な関係を省くものは何？","Purity (=Expand your own divine realm* develop a powerful barrier /sexual relationship)","純潔",new String[]{"「感情に所属しており、七大罪の対義語に位置している」","清らかであること","潔白であること","純真であること","無垢であること","清廉であること","道徳的に清らかである状態"}));
        questions.add(new Question("全情報閲覧とマッピングと追跡と魔道の極みと星魔から生み出され、拒否を省くものは何？","Wisdom (=View all information* mapping* tracking* The height of magic* Star demon /rejection)","叡智",new String[]{"「感情に所属しており、七大罪の対義語に位置している」","知識や理解を深めることに熱心であること","学問や研究を深めることに熱心であること","情報やデータを深めることに熱心であること","洞察や洞察力を深めることに熱心であること","真理や真実を深めることに熱心であること","知識や理解を追求し、賢明な判断を下す力"}));
        questions.add(new Question("深い悲しみと憎悪から至り、一つを除いてあらゆる感情が鎮静されるものは何？","Malice (=deep sorrow* hatred %It is every feeling except one)","悪意",new String[]{"「感情に所属しており、負の感情に位置している」","他人に対して強い敵意を持つこと","他人に対して強い憎しみを持つこと","他人に対して強い反感を持つこと","他人に対して強い嫌悪感を持つこと","他人に対して強い軽蔑を持つこと","他人に害を与えたり、不幸をもたらそうとする意図や願望"}));
        questions.add(new Question("殺し合う儀式と秘めた戦求本能から至り、全く同じものでは話にならないものは何？","Struggle (=The ceremony that it spoils* Hidden fighting instinct %It doesn't matter if it's exactly the same)","闘争",new String[]{"「感情に所属しており、負の感情に位置している」","他人と競い合うことを好むこと","他人と争うことを好むこと","他人と戦うことを好むこと","他人と対立することを好むこと","他人と競争することを好むこと","争いや競争を通じて自己を高めようとする心"}));
        questions.add(new Question("愛も欲も自分の中と気付けない存在が謳うから至り、心の中を探すものは何？","Intention to kill (=As for the love and the desire among oneself* Existence not to be able to notice declares it →I can look for it in a heart)","殺意",new String[]{"「感情に所属しており、負の感情に位置している」","他人を殺そうとする強い意図を持つこと","他人を傷つけようとする強い意図を持つこと","他人を害しようとする強い意図を持つこと","他人を排除しようとする強い意図を持つこと","他人を消滅させようとする強い意図を持つこと","他人を殺すことを望む心"}));
        questions.add(new Question("個体の減少と星から存在しなくなるから至り、バランスが破損するものは何？","Extinction (=Decrease in individuals* cease to exist from the stars →balance is damaged)","絶滅",new String[]{"「感情に所属しており、負の感情に位置している」","種や集団が完全に消滅すること","生物が完全に消滅すること","個体が完全に消滅すること","生命が完全に消滅すること","存在が完全に消滅すること","ある種や集団が完全に消滅し、二度と存在しなくなる状態"}));
        questions.add(new Question("死亡するフラグと成長するスピード速遅から至り、創造の先にあるものは何？","Catastrophe (=flag to die* growing fast and slow →beyond creation","破滅",new String[]{"「感情に所属しており、負の感情に位置している」","国家や文明が完全に崩壊すること","社会や文化が完全に崩壊すること","組織や制度が完全に崩壊すること","体制や秩序が完全に崩壊すること","構造やシステムが完全に崩壊すること","ある国家や文明が完全に崩壊し、二度と復活しない状態"}));
        questions.add(new Question("破局的な被害を受けると失い陥った運命から至り、回避したいと思うものは何？","Destruction (=suffer catastrophic damage* The fate I lost →want to avoid)","滅亡",new String[]{"「感情に所属しており、負の感情に位置している」","国家や文明が完全に崩壊すること","社会や文化が完全に崩壊すること","組織や制度が完全に崩壊すること","体制や秩序が完全に崩壊すること","構造やシステムが完全に崩壊すること","ある国家や文明が完全に崩壊し、二度と復活しない状態"}));
        questions.add(new Question("「それは聖なる力、それは未知への冒険、そしてそれは勇気の証」を変換したものは何？","Magic (=It's holy power, it's an adventure into the unknown, and it's a proof of courage.)","魔法",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","超自然的な力を操る能力","神秘的な力を操る能力","霊的な力を操る能力","神聖な力を操る能力","未知の力を操る能力","超自然的な力を使って現実世界に影響を与える能力"}));
        questions.add(new Question("輝く精神を変換したものは何？","Chiramental (=shining spirit)","キラメンタル",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","明るく輝く心の状態","希望に満ちた心の状態","前向きな心の状態","楽観的な心の状態","幸福な心の状態","明るく輝く精神状態"}));
        questions.add(new Question("自分だけの何かを変換したものは何？","Gotcha (=something just for me)","ガッチャ！",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","独自の特別なもの","個人的な特別なもの","唯一無二の特別なもの","独自性のある特別なもの","個性的な特別なもの","自分だけの特別な何か"}));
        questions.add(new Question("忍者に対して抱く各々の心の在り方や精神の持ち方と言った精神力を変換したものは何？ ","Shinobi Tality (=Mental strength, such as the way each person's heart and spirit is held toward ninjas)","忍タリティ",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","忍者としての精神力","忍者としての心構え","忍者としての精神的な強さ","忍者としての心の在り方","忍者としての精神的な持ち方","忍者に対して抱く各々の心の在り方や精神の持ち方と言った精神力"}));
        questions.add(new Question("「創る、形成する」を変換したものは何？","Build (=Create, form)","ビルド",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","物事を構築する能力","物事を形成する能力","物事を組み立てる能力","物事を創造する能力","物事を発展させる能力","何かを創り出す、または形作る能力"}));
        questions.add(new Question("愛と平和を変換したものは何？","Love and peace (=love & peace)","ラブ＆ピース",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","愛と平和の象徴","愛と平和の理念","愛と平和の価値観","愛と平和の精神","愛と平和の概念","愛と平和を象徴するもの"}));
        questions.add(new Question("『「勇気(brave)」だけでなく滅びた小惑星にはなかったもので、共に燃え上がり、絶望を乗り越える人間の魂とされる心の力』を変換したものは何？ ","Brave (=``Not only 'brave', but also the power of the heart that was not present on the destroyed asteroid, and is said to be the human spirit that burns together and overcomes despair.'')","ブレイブ",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","勇気と希望の象徴","勇気と希望の理念","勇気と希望の価値観","勇気と希望の精神","勇気と希望の概念","勇気と希望を象徴するもの"}));
        questions.add(new Question("想像力を変換したものは何？","Imagination (=imagination)","イマジネーション",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","創造的な思考力","独創的な思考力","革新的な思考力","斬新な思考力","発想力豊かな思考力","新しいアイデアや概念を生み出す能力"}));
        questions.add(new Question("マイペースに「行く」を変換したものは何？","It's mocha (=go at your own pace)","モカってる",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","自分のペースで進むこと","自分のリズムで進むこと","自分のスタイルで進むこと","自分の方法で進むこと","自分の速度で進むこと","自分のペースで行動すること"}));
        questions.add(new Question("「頑張っている」を変換したものは何？","I'm confused (=doing my best)","ツグってる",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","努力している状態","奮闘している状態","励んでいる状態","勤勉に取り組んでいる状態","熱心に取り組んでいる状態","一生懸命に頑張っている状態"}));
        questions.add(new Question("可愛いものに目がない様を変換したものは何？","Noah is here (=It's like you don't have an eye for cute things)","ノアってる",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","可愛いものに夢中になること","可愛いものに惹かれること","可愛いものに魅了されること","可愛いものに心奪われること","可愛いものに没頭すること","可愛いものに目がない様子"}));
        questions.add(new Question("自分を認めてくれる相手には甘えていくが、そうでない相手にはガードが堅い様を変換したものは何？","be disgusted with (=So that I behave like a baby to a partner detecting oneself, but guard is firm for the partner who is not so)","むにってる",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","親しい相手にだけ心を開くこと","信頼できる相手にだけ心を開くこと","安心できる相手にだけ心を開くこと","理解してくれる相手にだけ心を開くこと","共感してくれる相手にだけ心を開くこと","自分を認めてくれる相手にだけ心を許す様子"}));
        questions.add(new Question("感情を持つAI（機械族）が感情を持たないAI（機械族）のような行動を取る様を変換したものは何？","luminous (=The way an AI (machine people) with emotions behaves like an AI (machine people) without emotions.)","ルミナってる",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","感情を抑制すること","感情を制御すること","感情を抑えること","感情を管理すること","感情を調整すること","感情を持つAIが感情を持たないAIのような行動を取る様子"}));
        questions.add(new Question("何とも言い表せない素敵な気持ちを変換したものは何？","Emotional (=What an indescribably wonderful feeling!)","エモい",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","感動的な気持ち","胸が熱くなる気持ち","心が揺さぶられる気持ち","心が震える気持ち","心が動かされる気持ち","何とも言い表せない素敵な気持ち"}));
        questions.add(new Question("小さいもの、弱いものなどに心惹かれる気持ちを抱く様を変換したものは何？","Cute (=Feeling attracted to small and weak things)","可愛い",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","小さいものに心惹かれること","弱いものに心惹かれること","愛らしいものに心惹かれること","守りたいものに心惹かれること","無力なものに心惹かれること","小さいもの、弱いものなどに心惹かれる様子"}));
        questions.add(new Question("素晴らしい、最高を変換したものは何？","precious (=wonderful, the best)","尊い",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","非常に価値のあること","非常に貴重なこと","非常に崇高なこと","非常に偉大なこと","非常に卓越したこと","非常に素晴らしいこと"}));
        questions.add(new Question("時間が重なってできたもの、特定の事象を変換したものは何？","Memory (=Something created by the overlap of time, a specific event)","記憶",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","過去の出来事の記録","経験や体験の記録","思い出や思考の記録","情報や知識の記録","歴史や文化の記録","時間が重なってできたもの、特定の事象の記録"}));
        questions.add(new Question("存在の数だけ存在する、理想の具現化、偽善、正しい道理を変換したものは何？","justice (=embodiment of the ideal,hypocrisy,correct reason, a righteous principle that exists as many as there are)","正義",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","公平で公正な行動や判断","道徳的で倫理的な行動や判断","誠実で正直な行動や判断","責任感のある行動や判断","尊厳を守る行動や判断","公平で公正な行動や判断の概念"}));
        questions.add(new Question("姓名も社会も文明も全て無に還す事を変換したものは何？","absolute evil (=Names, society, and civilization will all be reduced to nothing.)","絶対悪",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","完全な悪の存在","究極の悪の存在","絶対的な悪の存在","無限の悪の存在","究極的な悪の存在","全てを無に還す完全な悪の存在"}));
        questions.add(new Question("運命共同体を変換したものは何？","Band (=Common destiny)","バンド",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","共に運命を共有する集団","共に未来を共有する集団","共に目標を共有する集団","共に挑戦を共有する集団","共に困難を共有する集団","運命を共にする集団"}));
        questions.add(new Question("「ダンス・クラブやディスコでレコードを選択し、プレーする人」、存在と音楽を繋ぐのを変換したものは何？","DJ (=``The person who selects and plays records at dance clubs and discos'', the person who connects existence and music.)","DJ",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","音楽を選択し再生する人","音楽をミックスし再生する人","音楽を編集し再生する人","音楽を操作し再生する人","音楽を演奏し再生する人","音楽を選択し、繋げて再生する人"}));
        questions.add(new Question("多数の要素が集まって（手）まとまりを持った組織や体系のことを変換したものは何？","System (=An organization or system in which many elements come together in a cohesive manner.)","システム",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","複数の要素が連携する仕組み","複数の要素が協力する仕組み","複数の要素が統合する仕組み","複数の要素が調和する仕組み","複数の要素が結合する仕組み","多数の要素が集まってまとまりを持った仕組み"}));
        questions.add(new Question("非常に稀有な「才能」たる転職に関連した能力を変換したものは何？","Skill (=Ability related to changing jobs as a very rare “talent”)","技能",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","特定の分野での専門的な能力","特定の分野での熟練した能力","特定の分野での優れた能力","特定の分野での卓越した能力","特定の分野での秀でた能力","特定の分野で優れた能力や技術"}));
        questions.add(new Question("「攻撃・防御の正確さ、精密さ」を変換したものは何？","Technology (=Accuracy and precision of attack and defense)","技術",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","高度な操作能力","精密な操作能力","正確な操作能力","巧妙な操作能力","熟練した操作能力","攻撃・防御の正確さや精密さを示す能力"}));
        questions.add(new Question("「8種の系統を持ち、神聖力を消費する」を変換したものは何？ ","Sacred art (=It has 8 different strains and consumes divine power.)","神聖術",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","神聖な力を操る技術","神秘的な力を操る技術","霊的な力を操る技術","聖なる力を操る技術","超自然的な力を操る技術","神聖な力を使って現実世界に影響を与える技術"}));
        questions.add(new Question("歌を歌う事を変換したものは何？","Singing (=singing a song)","歌唱",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","音楽を表現する行為","メロディーを表現する行為","リズムを表現する行為","声を使って表現する行為","歌詞を使って表現する行為","音楽を声で表現する行為"}));
        questions.add(new Question("分からないことにルールを探す地道な努力を変換したものは何？","Science (=Steady efforts to find rules for things we don't understand)","科学",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","自然現象を理解する学問","物理現象を理解する学問","化学現象を理解する学問","生物現象を理解する学問","宇宙現象を理解する学問","自然界の法則や現象を体系的に研究する学問"}));
        questions.add(new Question("音による芸術、器楽と声楽がある、人間に秘められた力を開放するものを変換したものは何？","Music (=Art by sound, instrumental music and vocal music, something that releases the power hidden in humans.)","音楽",new String[]{"「感情に所属しており、基本感情、弱い感情、強い感情、応用感情のどれにも位置しない」","音を使った芸術形式","メロディーを使った芸術形式","リズムを使った芸術形式","ハーモニーを使った芸術形式","サウンドを使った芸術形式","音を使って表現される芸術形式"}));
        questions.add(new Question("時空全体、前後左右上下に広がる空間と過去から未来に伸びる時間をひっくるめたもの、「共感覚によって曲が変わる度に会場全体の音、人の気持ちの色が変わる」を変換したものは何？","Universe (=The entire space and time, a space that extends forward, backward, left, right, up and down, and time that extends from the past to the future.``Every time the song changes due to synesthesia, the sound of the entire venue and the color of people's feelings change.'')","宇宙",new String[]{"概念に位置している","全ての存在と現象を包含する広大な空間","全ての物質とエネルギーを包含する広大な空間","全ての生命と意識を包含する広大な空間","全ての時間と空間を包含する広大な空間","全ての次元と現実を包含する広大な空間","時空全体を包含する広大な空間"}));
        questions.add(new Question("星の理を捻じ曲げる理法術と呼ばれる魔法の名を示す、下界に神の居る時代を変換したものは何？","Age of gods (=An era in which there were gods in the lower world, showing the name of the magic known as Logic that twisted the principles of the stars.)6","神代",new String[]{"概念に位置している","神々が支配していた時代","神々が存在していた時代","神々が治めていた時代","神々が繁栄していた時代","神々が栄えていた時代","神々が地上を支配していた時代"}));
    }

    public Question getRandomQuestion() {
        Random random = new Random();
        int index = random.nextInt(questions.size());
        return questions.get(index);
    }
}